version: '3.8'

services:
  motioncollisionweatherforecast:
    image: motioncollisionweatherforecast
    container_name: motioncollisionweatherforecast
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5080:80"
